licencjat/config/routes.rb
Rails.application.routes.draw do

  get 'error/not_found'

  devise_for :users
  root to: 'static_pages#home'

  get 'static_pages/home'

  get 'static_pages/tips'

  get 'static_pages/trips'

  get 'static_pages/fairs'

  get 'static_pages/museums'

  get 'static_pages/search'

  get 'tag/show'

  get 'static_pages/search_model/:id' => 'static_pages#search_model'

  resources :propositions, only: [:new, :create, :show]

  match '/propositions', to: 'propositions#new', via: 'get'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :attractions

  resources :categories

  resources :regions

  resources :tag

  resources :varieties

  get "*any", via: :all, to: "error#not_found"
end

licencjat/app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]
  authorize_resource only: [:update, :delete, :edit, :create, :new]


  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
    @regions = Region.all
    #@varieties = Variety.all
    @categories =Category.all
    @variety = Variety.find(params[:name])
  end

  def tagged

    if params[:tag].present?
      @attractions = Attraction.tagged_with(params[:tag])
    else
      @attractions = Attraction.all.order("created_at DESC")
    end
  end



  # GET /attractions/1
  # GET /attractions/1.json
  def show
    @categories =Category.all
    @attractions = Attraction.tagged_with(params[:tag])
    @hash = Gmaps4rails.build_markers(@attractions) do |attraction, marker|
      marker.lat attraction.latitude
      marker.lng attraction.longitude
      marker.infowindow attraction.name
      marker.picture({
                         "url" => "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
                         "width" => 32,
                         "height" => 32
                     })
    end
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
    @categories = Category.all
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :description, :address, :opening_hour, :duration, :reservation,
                                         :more_info, :picture, :url, :category_id, :region_id, :latitude, :longitude,
                                         :tag_list, :tag, :variety_id)
    end



end

licencjat/app/helpers/attractions_helper.rb
module AttractionsHelper
  include ActsAsTaggableOn::TagsHelper
end

licencjat/app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :opening_hour %><br>
    <%= f.text_field :opening_hour %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :reservation %><br>
    <%= f.text_field :reservation %>
  </div>
  <div class="field">
    <%= f.label :more_info %><br>
    <%= f.text_area :more_info %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_area :picture %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
    <div class="field">
      <%= f.label :name, "Region" %><br />
      <%= f.collection_select :region_id, Region.all,:id,:name, prompt: true %>
    </div>
    <div class="field">
      <%= f.label :name, "Kategoria" %><br />
      <%= collection_select :attraction, :category_id, Category.all,:id,:name, prompt: true %>
    </div>
    <div class="field">
      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
      <%= f.text_field :tag_list %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

licencjat/app/views/attractions/edit.html.erb
<h1>Editing Attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

licencjat/app/views/attractions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attractions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Opening hour</th>
      <th>Duration</th>
      <th>Reservation</th>
      <th>More info</th>
      <th>Picture</th>
      <th>Url</th>
      <th>Category</th>
      <th>Region</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= attraction.name %></td>
        <td><%= attraction.description %></td>
        <td><%= attraction.address %></td>
        <td><%= attraction.opening_hour %></td>
        <td><%= attraction.duration %></td>
        <td><%= attraction.reservation %></td>
        <td><%= attraction.more_info %></td>
        <td><%= attraction.picture %></td>
        <td><%= attraction.url %></td>
        <td><%= attraction.category_id %></td>
        <td><%= attraction.region_id %></td>
        <td><%= attraction.latitude %></td>
        <td><%= attraction.longitude %></td>
        <td><% attraction.tags.each do |tag| %>
              <%= link_to tag, tag_path(tag) %>
          <% end %></td>
        <td><%= link_to 'Show', attraction %></td>
        <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attraction', new_attraction_path %>

licencjat/app/views/attractions/new.html.erb
<p id="notice"><%= notice %></p>


<div class="container-fluid"
<%= render template: "layouts/menu" %>

</div>
<br />
<div class="container">
  <div class="col-md-9 col-sm-7">
<div class="jumbotron">
    <form data-toggle="validator" role="form">
  <form role="form">
    <div class="form-group ">
      <label >E-mail</label>
      <input type="email" class="form-control" id="inputEmail" placeholder="E-mail" data-error="Podany adres e-mail
      jest niepoprawny" required>
      <div class="help-block with-errors"></div>
    </div>
    <div class="form-group has-success">
      <label>Treść</label>
      <textarea class="form-control" rows="3" data-minlength="10"
                placeholder="Wpisz propozycję atrakcji..." required></textarea>
      <span class="help-block with-errors">Twoja wiadomość powinna zawierać więcej niż 10 znaków.</span>
    </div>
    <div class="form-group has-success">
      <label>Podaj adres źródła</label>
      <input class="form-control" name="website"
             type="url"
             data-fv-uri-message="Niepoprawny adres. Spróbuj wpisać jeszcze raz." placeholder="Adres źródła..."/>
    </div>
    <button type="submit" class="btn btn-success pull-right">Wyślij!</button>
  </form>
        </form>
  </div>
</div>

  <div class="col-md-3 col-xs-5 ">
    <%= render template: "layouts/right-side" %>
  </div>

</div>

  <%= link_to 'Back', attractions_path %>
</div>
<div class="container-fluid">
  <%= render template: "layouts/footer" %>
</div>

licencjat/app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<%= render template: "layouts/logo+menu" %>
<div class="container">

  <div class="col-md-3 col-sm-3">

    <%= image_tag('300.gif', alt: 'toooor', width: "250px",height: "250px" ) %>
  </div>

  <div class="col-md-6 col-sm-9 well">


  <h2><%= @attraction.name %></h2>



<p>
  <strong>Description:</strong>
  <%= @attraction.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @attraction.address %>
</p>

<p>
  <strong>Opening hour:</strong>
  <%= @attraction.opening_hour %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @attraction.duration %>
</p>

<p>
  <strong>Reservation:</strong>
  <%= @attraction.reservation %>
</p>

<p>
  <strong>More info:</strong>
  <%= @attraction.more_info %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @attraction.picture %>
</p>

<p>
  <strong>Url:</strong>
  <%= @attraction.url %>
</p>
    <br /><br />

<p class="pull-right">


     <span class="label label-success btn-link"> <%= link_to @attraction.category.name, category_path
     %></span>

      <span class="label label-success btn-link"><%= link_to @attraction.region.name, region_path
      %></span>

<% @attraction.tags.each do |tag| %>
        <span class="label label-success btn-link"><%= link_to tag.name,  tag_path(tag)%></span>

  <% end %>

</p>

<br /><br /><br /><br />
<div >
  <div id="multi_markers" class="center-block" style='width: 500px; height: 300px;'></div>
</div>


<script type="text/javascript">

    var szer = <%= @attraction.latitude %>;
    var dlu = <%= @attraction.longitude %>;
    var naz = '<%= @attraction.name %>';

    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: {id: 'multi_markers'}}, function(){
        var markers = handler.addMarkers([
            {

                lat: szer, lng: dlu,
                infowindow: '$naz'.replace('$naz', naz)


            }
        ]);

        handler.bounds.extendWith(markers);

        handler.fitMapToBounds();
        handler.getMap().setZoom(15);

    });

</script>

  </div>
  <div class="col-md-3 col-xs-5 ">

    <%= render template: "layouts/right-side" %>

  </div>
  </div>

  <%= link_to 'Edit', edit_attraction_path(@attraction) %>|
  <%= link_to 'Back', attractions_path %>

<div>
  <%= render template: "layouts/footer" %>
</div>