licencjat/config/routes.rb
Rails.application.routes.draw do

  get 'error/not_found'

  devise_for :users
  root to: 'static_pages#home'

  get 'static_pages/home'

  get 'static_pages/tips'

  get 'static_pages/trips'

  get 'static_pages/fairs'

  get 'static_pages/museums'

  get 'static_pages/search'

  get 'tag/show'

  get 'static_pages/search_model/:id' => 'static_pages#search_model'

  resources :propositions, only: [:new, :create, :show]

  match '/propositions', to: 'propositions#new', via: 'get'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :attractions

  resources :categories

  resources :regions

  resources :tag

  resources :varieties

  get "*any", via: :all, to: "error#not_found"
end

licencjat/app/models/static_page.rb
class StaticPage < ActiveRecord::Base


  def random
    offset(rand(count))
  end

  def get_random
    Attraction.limit(5).order("RANDOM()")
  end
end

licencjat/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_authorization_check
  include VarietiesHelper

  def home
    @categories= Category.all
  end

  def tips
    @categories= Category.all
    @attractions=Attraction.all
  end

  def trips
    @variety = Variety.find_by_id(1)

    @attractions=Attraction.all
    @varieties=Variety.all

    @categories= Category.all
    #@attractions= @attractions.variety.name
   # @attraction = Attraction.find(params[:id])
   # @attr = @varieties.attractions



  end

  def fairs
    @variety = Variety.find_by_id(3)
    @categories= Category.all
    @attractions=Attraction.all
  end

  def museums
    @variety = Variety.find_by_id(2)
    @categories= Category.all
    @attractions=Attraction.all
  end

  def search
    @categories= Category.all
  end

  def search_model
    binding.pry
    @category = Category.search(params[:id])
  end
end

licencjat/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

licencjat/app/views/static_pages/fairs.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Rozwiń nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">"Logo strony"</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Wycieczki po fabrykach", static_pages_trips_path %></li>
        <li class="active"><%= link_to "Targi technologiczne", static_pages_fairs_path %><span class="sr-only">
          (current)</span></li>
        <li><%= link_to "Muzea techniczne", static_pages_museums_path %></li>
        <li><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
        <li><%= link_to "Wyszukiwarka atrakcji", static_pages_search_path %></li>

      </ul>

    </div>
  </div>
</nav>
</div>
</nav>
<div class="container">


  <div class="col-md-9 col-sm-9">
    <h1>Nagłówek</h1>


    <p class="lead">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
      amet,
      consectetur adipiscing elit.
    </p>
    <br \>

    <h2>Najpopularniejsze targi technologiczne</h2>
    <br \>

    <% @variety.attractions.limit(3).order("RANDOM()").each do |attraction| %>
        <div class="col-md-4 text-center">
          <table class="table table-striped table-hover ">
            <tbody>
            <tr class="success">
              <td>
                <div>
                  <%= link_to attraction_path(attraction) do %>
                      <%= image_tag('300.gif', alt: 'toooor', width: "250px", height: "200px", class:
                                                     "story-img") %>
                  <% end %>
                </div>


                <div><h3><%= attraction.name %> </h3></div>
                <div>  <%= attraction.description %>  </div>
                <div> <%= link_to "Zobacz więcej", attraction_path(attraction) %>   </div>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
    <% end %>

    <div class="container"></div>

    <div class="col-md-12 text-center">
      <% if @variety.attractions.count > 0 %>


              <%= button_to "Zobacz wszystkie", variety_path(@variety.id),
                            :class => "btn btn-success btn-lg", :method => :get %>


      <% else %>

          <div class="alert alert-dismissible alert-warning text-uppercase">

            <h4>Uwaga!</h4>

            <p>
              <%= @variety.name %> nie są obecnie dostępne!
            </p>
          </div>

      <% end %>

    </div>

  </div>
  <div class="col-md-3 col-xs-3 ">
    <%= render template: "layouts/right-side" %>
  </div>
</div>

<br \><br \><br \>
<div>
  <%= render template: "layouts/footer" %>
</div>

licencjat/app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="jquery.min.js"></script>
  <script src="social-likes.min.js"></script>
  <meta name="generator" content="Social Likes: http://sapegin.github.com/social-likes/">
  <link rel="stylesheet" href="social-likes_birman.scss">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
  <div class="container">
    <div class="row">
      <div class="col col-lg-12 col-sm-12">
        <h1>LOGO</h1>

        <p>jakieś</p>

      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-default ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Rozwiń nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">"Logo strony"</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", static_pages_home_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to "Wycieczki po fabrykach", static_pages_trips_path %></li>
        <li><%= link_to "Targi technologiczne", static_pages_fairs_path %></li>
        <li><%= link_to "Muzea techniczne", static_pages_museums_path %></li>
        <li><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
        <li><%= link_to "Wyszukiwarka atrakcji", static_pages_search_path %></li>

      </ul>

    </div>
  </div>
</nav>
<div class="container">


  <div class="col-md-3 col-sm-3">
    <%= image_tag('300.gif', alt: 'Zdjęcie', width: "250px", height: "200px", class:
                                   "story-img") %>
  </div>

  <div class="col-md-6 col-sm-3">
    <h1>Nagłówek</h1>


    <p class="lead">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
      amet,
      consectetur adipiscing elit.
    </p>

    <p>Curabitur consequat, leo in sodales sollicitudin, sem eros pellentesque diam, sit amet
      imperdiet est velit eu tellus. Curabitur neque eros, bibendum a augue eget, luctus accumsan turpis.
      Vivamus uscipit, felis sit amet venenatis accumsan, urna purus vestibulum purus, ac porta sapien turpis at massa.
      Phasellus ante purus, fringilla in justo quis, convallis commodo felis. Sed vel ex id lorem egestas faucibus eget
      vitae lorem. Integer faucibus ullamcorper dui, sit amet viverra sapien sodales vel. Nulla ante nibh, vulputate a
      gravida vel, semper vel nisi. Nam quis ligula vulputate, elementum libero eu, feugiat massa. Pellentesque habitant
      morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam in tincidunt enim, non euismod dui.
    </p>


    <div>
      <p>
        <%= button_to "Znajdź atrakcję", static_pages_search_path, :class => "btn btn-success pull-right", :method =>
                                               :get %>
      </p>


      <div class="social-likes social-likes_single pull-right" data-counters="no" data-single-title="Share">
        <div class="facebook" title="Share link on Facebook">Facebook</div>
        <div class="twitter" title="Share link on Twitter">Twitter</div>
        <div class="plusone" title="Share link on Google+">Google+</div>
      </div>
    </div>
  </div>
  <br \><br \><br \><br \>

  <div class="col-md-3 col-xs-5 ">
    <%= render template: "layouts/right-side" %>


  </div>
</div>
<br \><br \><br \>

<div class="container-fluid">
  <%= render template: "layouts/footer" %>
</div>
</body>

licencjat/app/views/static_pages/museums.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Wycieczki po fabrykach", static_pages_trips_path %></li>
        <li><%= link_to "Targi technologiczne", static_pages_fairs_path %></li>
        <li class="active"><%= link_to "Muzea techniczne", static_pages_museums_path %><span class="sr-only">
          (current)</span></li>
        <li><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
        <li><%= link_to "Wyszukiwarka atrakcji", static_pages_search_path %></li>

      </ul>

    </div>
  </div>
</nav>

<div class="container">


  <div class="col-md-9 col-sm-9">
    <h1>Nagłówek</h1>


    <p class="lead">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
      amet,
      consectetur adipiscing elit.
    </p>
    <br />

    <h2>Najpopularniejsze muzea techniczne</h2>
    <br />

    <% @variety.attractions.limit(3).order("RANDOM()").each do |attraction| %>
        <div class="col-md-4 text-center">
          <table class="table table-striped table-hover success">

            <tbody>
            <tr class="success">
              <td>
                <div>
                  <%= link_to attraction_path(attraction) do %>
                      <%= image_tag('300.gif', alt: attraction.name, width: "250px", height: "200px", class:
                                                     "story-img") %>
                  <% end %>
                </div>
                <div><h3> <%= attraction.name %> </h3></div>
                <div> <%= attraction.description %>  </div>
                <div> <%= link_to "Zobacz więcej", attraction_path(attraction) %>   </div>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
    <% end %>

    <div class="container"></div>
    <% if @variety.attractions.count > 0 %>
        <div class="col-md-12 text-center">



              <%= button_to "Zobacz wszystkie", variety_path(@variety.id),
                            :class => "btn btn-success btn-lg", :method => :get %>
         

    <% else %>

        <div class="alert alert-dismissible alert-danger">

          <h4>Uwaga!</h4>

          <p>
            <%= @variety.name %> nie są obecnie dostępne!
          </p>
        </div>


        </div>
    <% end %>
  </div>

</div>
  <div class="col-md-3 col-sm-3 ">
    <%= render template: "layouts/right-side" %>
  </div>
</div>
<br \><br \><br \>
<div>
  <%= render template: "layouts/footer" %>
</div>

licencjat/app/views/static_pages/search.html.erb
<!DOCTYPE html>
<html>
<head>


</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Rozwiń nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">"Logo strony"</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Wycieczki po fabrykach", static_pages_trips_path %></li>
        <li><%= link_to "Targi technologiczne", static_pages_fairs_path %></li>
        <li><%= link_to "Muzea techniczne", static_pages_museums_path %></li>
        <li><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
        <li class="active"><%= link_to"Wyszukiwarka atrakcji", static_pages_search_path %><span class="sr-only">(current)</span></li>

      </ul>

    </div>
  </div>
</nav>

<div class="container">
  <div class="col-md-9 col-sm-8">

    <%= form_tag('search_model/1', method: :get) do %>
        <%= label_tag(:q, "Search for") %>
        <%= submit_tag("Search123") %>
      <div class="form-group">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Szukaj...">

        </div>

        <div class="field ">
            <%= label :category, "Kategoria" %><br />
            <%= select_tag(:category_id, options_from_collection_for_select(Category.all, 'id', 'name'), :prompt => "Select
              one!") %>
         </div>
        <div class="field">
            <%= label :region, "Region" %><br />
            <%= select_tag(:region_id, options_from_collection_for_select(Region.all, 'id', 'name'), :prompt => "Select
          one!") %>
        </div>

        <div class="checkbox">
            <label><input type="checkbox" value="">Wycieczki po fabrykach</label>
        </div>
        <div class="checkbox">
            <label><input type="checkbox" value="">Targi technologiczne</label>
        </div>
        <div class="checkbox">
            <label><input type="checkbox" value="" >Muzea techniczne</label>
        </div>
        <div class="checkbox">
            <label><input type="checkbox" value="" >Zaznacz wszystkie</label>
        </div>

        <button class="btn btn-success pull-right" type="button"><span class="glyphicon glyphicon-search"
                                                      aria-hidden="true"> Szukaj</span></button>

      </div>
    <% end %>
  </div>

  <div class="col-md-3 col-xs-5">
    <%= render template: "layouts/right-side" %>
  </div>

  </div>
<br \><br \><br \>
<div>
  <%= render template: "layouts/footer" %>
</div>
</body>

licencjat/app/views/static_pages/search_model.erb
coścoś

licencjat/app/views/static_pages/tips.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Rozwiń nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">"Logo strony"</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Wycieczki po fabrykach", static_pages_trips_path %></li>
        <li><%= link_to "Targi technologiczne", static_pages_fairs_path %></li>
        <li><%= link_to "Muzea techniczne", static_pages_museums_path %></li>
        <li class="active"><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %><span class="sr-only">
          (current)</span></li>
        <li><%= link_to"Wyszukiwarka atrakcji", static_pages_search_path %></li>

      </ul>

    </div>
  </div>
</nav>

<div class="container">
  <div class="col-md-9 col-sm-8">
  <div class="panel-group" id="accordion">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
            Collapsible Group Item #1
          </a>
        </h4>
      </div><!--/.panel-heading -->
      <div id="collapseOne" class="panel-collapse collapse in">
        <div class="panel-body">
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </div><!--/.panel-body -->
      </div><!--/.panel-collapse -->
    </div><!-- /.panel -->

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
            Collapsible Group Item #2
          </a>
        </h4>
      </div><!--/.panel-heading -->
      <div id="collapseTwo" class="panel-collapse collapse">
        <div class="panel-body">

          <!-- nested -->


          <div class="panel-group" id="nested">

            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#nested" href="#nested-collapseOne">
                    Collapsible Group Item #1
                  </a>
                </h4>
              </div><!--/.panel-heading -->
              <div id="nested-collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div><!--/.panel-body -->
              </div><!--/.panel-collapse -->
            </div><!-- /.panel -->

            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a class="collapsed" data-toggle="collapse" data-parent="#nested" href="#nested-collapseTwo">
                    Collapsible Group Item #2
                  </a>
                </h4>
              </div><!--/.panel-heading -->
              <div id="nested-collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div><!--/.panel-body -->
              </div><!--/.panel-collapse -->
            </div><!-- /.panel -->

            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a class="collapsed" data-toggle="collapse" data-parent="#nested" href="#nested-collapseThree">
                    Collapsible Group Item #3
                  </a>
                </h4>
              </div><!--/.panel-heading -->
              <div id="nested-collapseThree" class="panel-collapse collapse">
                <div class="panel-body">
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div><!--/.panel-body -->
              </div><!--/.panel-collapse -->
            </div><!-- /.panel -->
          </div><!-- /.panel-group -->


          <!-- nested -->


        </div><!--/.panel-body -->
      </div><!--/.panel-collapse -->
    </div><!-- /.panel -->

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
            Collapsible Group Item #3
          </a>
        </h4>
      </div><!--/.panel-heading -->
      <div id="collapseThree" class="panel-collapse collapse">
        <div class="panel-body">
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </div><!--/.panel-body -->
      </div><!--/.panel-collapse -->
    </div><!-- /.panel -->
  </div><!-- /.panel-group -->


    </div>
<div class="col-md-3 col-xs-5">
  <%= render template: "layouts/right-side" %>
</div>
</div><!-- /.container -->
<br \><br \><br \>
<div>
  <%= render template: "layouts/footer" %>
</div>

licencjat/app/views/static_pages/trips.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Rozwiń nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">"Logo strony"</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li class="active"><%= link_to "Wycieczki po fabrykach", static_pages_trips_path %><span class="sr-only">
          (current)</span></li>
        <li><%= link_to "Targi technologiczne", static_pages_fairs_path %></li>
        <li><%= link_to "Muzea techniczne", static_pages_museums_path %></li>
        <li><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
        <li><%= link_to "Wyszukiwarka atrakcji", static_pages_search_path %></li>

      </ul>

    </div>
  </div>
</nav>
</div>
</nav>
<div class="container">


  <div class="col-md-9 col-sm-9">
    <h1>Nagłówek</h1>


    <p class="lead">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed interdum sapien. Lorem ipsum dolor sit
      amet,
      consectetur adipiscing elit.
    </p>
    <br \>

    <h2>Najpopularniejsze wycieczki</h2>
    <br \>

    <% @variety.attractions.limit(3).order('RANDOM()').each do |attraction| %>
        <div class="col-md-4 text-center">
          <table class="table table-striped table-hover ">
            <tbody>
            <tr class="success">
              <td>
                <div>
                  <%= link_to attraction_path(attraction) do %>
                      <%= image_tag('300.gif', alt: attraction.name, width: "250px", height: "200px", class:
                                                     "story-img") %>
                  <% end %>
                </div>

                <div><h3><%= attraction.name %> </h3></div>
                <div>  <%= attraction.description %>  </div>
                <div> <%= link_to "Zobacz więcej", attraction_path(attraction) %>   </div>
              </td>
            </tr>
            </tbody>
          </table>
        </div>

    <% end %>
    <div class="container"></div>

    <div class="col-md-12 text-center">

      <% if @variety.attractions.count > 0 %>


              <%= button_to "Zobacz wszystkie", variety_path(@variety.id),
                            :class => "btn btn-success btn-lg", :method => :get %>




      <% else %>

          <div class="alert alert-dismissible alert-danger text-uppercase">

            <h4>Uwaga!</h4>

            <p>
              <%= @variety.name %> nie są obecnie dostępne!
            </p>
          </div>

      <% end %>

    </div>

  </div>


  <div class="col-md-3 col-xs-5 ">
    <%= render template: "layouts/right-side" %>
  </div>
</div>
<br \><br \><br \>
<div>
  <%= render template: "layouts/footer" %>
</div>