licencjat/config/routes.rb
Rails.application.routes.draw do

  get 'error/not_found'

  devise_for :users
  root to: 'static_pages#home'

  get 'static_pages/home'

  get 'static_pages/tips'

  get 'static_pages/trips'

  get 'static_pages/fairs'

  get 'static_pages/museums'

  get 'static_pages/search'

  get 'tag/show'

  get 'static_pages/search_model/:id' => 'static_pages#search_model'

  resources :propositions, only: [:new, :create, :show]

  match '/propositions', to: 'propositions#new', via: 'get'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :attractions

  resources :categories

  resources :regions

  resources :tag

  resources :varieties

  get "*any", via: :all, to: "error#not_found"
end

licencjat/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new
    can :manage, :all if user.admin?
  end

end

licencjat/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

licencjat/app/models/attraction.rb
class Attraction < ActiveRecord::Base


  belongs_to :region, :class_name => "Region", :foreign_key => :region_id
  belongs_to :category, :class_name => "Category", :foreign_key => :category_id
  belongs_to :variety, :class_name => "Variety", :foreign_key => :variety_id
  accepts_nested_attributes_for :category


  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  acts_as_taggable

  geocoded_by :address
  # geocoded_by :full_address # can also be an IP address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, :reverse_geocode # auto-fetch coordinates


  validates :name, presence: true, uniqueness: true, length: {within: 2..100}
  validates :description, presence: true, length: {minimum: 10}
  validates_presence_of :address, :opening_hour, :duration, :reservation, :picture
  validates_presence_of :region_id, :category_id, :variety_id
  validates_length_of :more_info, :minimum => 5, :allow_blank => true


  #geocoder
  #def full_address
  #   "#{address} Japan"
  # end
end

licencjat/app/models/category.rb
class Category < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :attractions
  accepts_nested_attributes_for :attractions

  validates :name, presence: true, length: {within: 2..100}

end

licencjat/app/models/proposition.rb
class Proposition < ActiveRecord::Base


  include MailForm::Delivery


    attributes :name, :validate => true
    attributes :email, format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i,
                                message: "Podaj adres e-mail" }
    attribute :message, :validate => true
    attribute :url, :presence => true, :format => URI::regexp(%w(http https))



    validates :email, format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i,
                                      message: "Podaj adres e-mail" }
    validates :email, :presence => true
    validates :message, :presence => true, length: {minimum:  10, too_short: 'Wiadomość musi być dłuższa niż %{count}
znaków.'}
    validates :url, :presence => true

    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.

    def headers
      {
          :subject => "Propozycja atrakcji",
          :to => "atrakcje.przemyslowe@gmail.com",
          :from => %("#{email}")
      }
    end

after_create

end

licencjat/app/models/region.rb
class Region < ActiveRecord::Base

  has_many :attractions


  validates :name, presence: true, length: {within: 2..100}


end

licencjat/app/models/static_page.rb
class StaticPage < ActiveRecord::Base


  def random
    offset(rand(count))
  end

  def get_random
    Attraction.limit(5).order("RANDOM()")
  end
end

licencjat/app/models/tag.rb
class Tag < ActiveRecord::Base
end

licencjat/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
    admin
  end

end

licencjat/app/models/variety.rb
class Variety < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :attractions
  accepts_nested_attributes_for :attractions

  validates :name, presence: true, length: {within: 2..100}


end

licencjat/app/controllers/tag_controller.rb
class TagController < ApplicationController
  authorize_resource only: [:update, :delete, :edit]

  def show
    @tag = Tag.find(params[:id])
    @attractions = Attraction.tagged_with(@tag.name)
    @categories = Category.all
  end
end

licencjat/app/helpers/application_helper.rb
module ApplicationHelper
end

licencjat/app/helpers/attractions_helper.rb
module AttractionsHelper
  include ActsAsTaggableOn::TagsHelper
end

licencjat/app/helpers/categories_helper.rb
module CategoriesHelper
end

licencjat/app/helpers/error_helper.rb
module ErrorHelper
end

licencjat/app/helpers/propositions_helper.rb
module PropositionsHelper
end

licencjat/app/helpers/regions_helper.rb
module RegionsHelper
end

licencjat/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

licencjat/app/helpers/tag_helper.rb
module TagHelper
  @tags = Attraction.tag_counts_on(:tags)
  ActsAsTaggableOn.force_lowercase = true
end

licencjat/app/helpers/varieties_helper.rb
module VarietiesHelper



end

licencjat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Licencjat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

</body>
</html>

licencjat/app/views/layouts/footer.erb
<div class="panel-footer">
  <div class="text-center text-success">
    <p>Created by Monika Malinowska</p>
  </div>
  <div class="pull-right text-success">
    <%= link_to "Panel administracyjny", '/admin/login', :method => 'get' %>
  </div>

</div>

licencjat/app/views/layouts/logo+menu.erb
<div class="jumbotron text-center">
  <div class="container">
    <div class="row">
      <div class="col col-lg-12 col-sm-12">
        <h1>LOGO</h1>
        <p>jakieś</p>

      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-default">
  <div class="container-fluid">


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Wycieczki po fabrykach", static_pages_trips_path %></li>
        <li><%= link_to "Targi technologiczne", static_pages_fairs_path %></li>
        <li><%= link_to "Muzea techniczne", static_pages_museums_path %></li>
        <li><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
        <li><%= link_to"Wyszukiwarka atrakcji", static_pages_search_path %></li>

      </ul>

    </div>
  </div>
</nav>

licencjat/app/views/layouts/menu.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Rozwiń nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">"Logo strony"</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Wycieczki po fabrykach", static_pages_trips_path %></li>
        <li><%= link_to "Targi technologiczne", static_pages_fairs_path %></li>
        <li><%= link_to "Muzea techniczne", static_pages_museums_path %></li>
        <li><%= link_to "Wskazówki dla podróżnych", static_pages_tips_path %></li>
        <li><%= link_to"Wyszukiwarka atrakcji", static_pages_search_path %></li>

      </ul>

    </div>
  </div>
</nav>

licencjat/app/views/layouts/right-side.erb
<div class="input-group">
  <input type="text" class="form-control" placeholder="Szukaj...">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button"><span class="glyphicon glyphicon-search"
                                                            aria-hidden="true"></span></button>
      </span>
</div>

<!--
    <form role="search">
      <div class="form-group">
        <input class="form-control glyphicon " placeholder="Szukaj" type="text">
      </div>
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Szukaj
      </button>
    </form>
-->
<br \>
<br \>
<h3>Tagi</h3>
<div class="well">

  <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, label| %>
    <span class="label label-success btn-link"> <%= link_to tag.name, tag_path(tag), :class =>
                                                                            label %></span>
  <% end %>

</div>
<br \>
<br \>

<div class="list-group ">
  <h3 class="list-group-item-heading ">Kategorie</h3>

  <ul>
    <% @categories.each do |c| %>
        <li class="list-group-item"><%= link_to c.name, category_path(c.id) %></li>

    <% end %>
  </ul>

</div>