licencjat/config/routes.rb
Rails.application.routes.draw do

  get 'error/not_found'

  devise_for :users
  root to: 'static_pages#home'

  get 'static_pages/home'

  get 'static_pages/tips'

  get 'static_pages/trips'

  get 'static_pages/fairs'

  get 'static_pages/museums'

  get 'static_pages/search'

  get 'tag/show'

  get 'static_pages/search_model/:id' => 'static_pages#search_model'

  resources :propositions, only: [:new, :create, :show]

  match '/propositions', to: 'propositions#new', via: 'get'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :attractions

  resources :categories

  resources :regions

  resources :tag

  resources :varieties

  get "*any", via: :all, to: "error#not_found"
end

licencjat/app/models/region.rb
class Region < ActiveRecord::Base

  has_many :attractions


  validates :name, presence: true, length: {within: 2..100}


end

licencjat/app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]
  authorize_resource only: [:update, :delete, :edit]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
    @categories = Category.all
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name)
    end
end

licencjat/app/helpers/regions_helper.rb
module RegionsHelper
end

licencjat/app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

licencjat/app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

licencjat/app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Regions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

licencjat/app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

licencjat/app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
<%= render template: "layouts/menu" %>
</div>
<div class="container">


  <div class="col-md-9 col-sm-9">
    <div>
    <p>

      Atrakcje znajdujące się w: <strong class="text-uppercase"><%= @region.name %></strong>
    </p>
    </div>
    <% if @region.attractions.count > 0 %>
    <table class="table table-striped table-hover ">
      <% @region.attractions.each do |attr| %>
          <tbody>

          <tr class="success">

            <td>
              <%= link_to attraction_path(attr) do %>
                  <%= image_tag('300.gif', alt: 'toooor', width: "100px", height: "100px", class:
                                                 "story-img ") %>
              <% end %>
</td>

            <td class="col-md-3"><%= attr.name %></td>
            <td class="col-md-5"><%= attr.description %></td>
            <td class="col-md-2"><%= link_to "Zobacz więcej", attraction_path(attr) %></td>

          </tr>



          </tbody>
      <% end %>
    </table>
    <% else %>

        <div class="alert alert-dismissible alert-danger">

          <h4>Uwaga!</h4>
          <p>W tym regionie nie ma żadnych atrakcji związanych z technologią.</p>
        </div>

    <% end %>

  </div>
  <div class="col-md-3 col-xs-5 ">
    <%= render template: "layouts/right-side" %>
  </div>



<%= link_to 'Edit', edit_region_path(@region) %>
<%= link_to 'Back', regions_path %>
</div>
<div>
  <%= render template: "layouts/footer" %>
</div>